project:
  type: book
  output-dir: docs


book:
  title: "Desarrollo de un Dispositivo Wearable para la Medición del Confort Térmico en Edificaciones"
  output-file: "tesis."
  author: "Julio César Landa López"
  date: "10/10/2023"
  language: "es"

  comments:
    hypothesis:
      theme: classic

  chapters:
    - index.qmd
    - Capitulos/intro.qmd
    - Capitulos/estado.qmd
    - Capitulos/metodologia.qmd
    - Capitulos/desarrollo.qmd
    - Capitulos/resultados.qmd
    - Capitulos/references.qmd

bibliography: Referencias/references.bib

format:
  html:
    theme: zephyr
  pdf:
    documentclass: scrreprt
    

