# Resumen {.unnumbered}

El confort térmico es un aspecto crucial para la calidad de vida de las personas, ya que afecta directamente su bienestar físico y mental. Además, desempeña un papel fundamental en el consumo energético de las edificaciones, donde una gran parte de la energía se destina a sistemas de calefacción, ventilación y aire acondicionado (HVAC, por sus siglas en inglés). Estos sistemas nos ayudan a mantener condiciones adecuadas de confort, sino que también contribuyen de manera indirecta a las emisiones de gases de efecto invernadero (GEI) y al cambio climático. Para mitigar este impacto climático, es fundamental integrar tecnologías accesibles y eficientes que permitan propiciar el confort térmico sin incrementar el consumo energético. Estrategias como el diseño bioclimático destacan por su capacidad para adaptarse y responder a las condiciones climáticas locales, reduciendo la dependencia de sistemas HVAC y contribuyendo a la sostenibilidad.

Este trabajo presenta el desarrollo de un reloj inteligente basado en tecnologías abiertas, diseñado para la recopilación de datos relacionados con el confort térmico. El reloj permite recopilar datos subjetivos a través de encuestas simplificadas de confort térmico, y registrar la medición de variables fisiológicas, tales como la temperatura de la piel y la frecuencia cardíaca. Los datos recopilados son enviados y almacenados en la plataforma ThingsBoard, lo que permite generar una base de datos contextualizada adaptable a diferentes contextos climáticos.

El reloj inteligente integra componentes de bajo costo, como la placa de desarrollo XIAO ESP32C3, los sensores GY-906 y MAX30102, una pantalla táctil XIAO Round Display, y un circuito vibrador, todo encapsulado en una carcasa diseñada e impresa en 3D. 

El desarrollo de este proyecto incluye el diseño, construcción, calibración y validación del dispositivo. Este trabajo destaca y demuestra el potencial de las tecnologías abiertas y los dispositivos portátiles en el estudio del confort térmico, así como en la generación de bases de datos que pueden facilitar la creación de modelos de confort adaptativos. De esta manera, se contribuye al uso sostenible de los recursos para lograr condiciones de confort térmico. \newline

# Abstract {.unnumbered}


Thermal comfort is a crucial aspect of people's quality of life, as it directly impacts their physical and mental well-being. Additionally, it plays a fundamental role in the energy consumption of buildings, where a significant portion of energy is allocated to heating, ventilation, and air conditioning (HVAC) systems. While these systems help maintain suitable comfort conditions, they also indirectly contribute to greenhouse gas (GHG) emissions and climate change. To mitigate this climate impact, it is essential to integrate accessible and efficient technologies that promote thermal comfort without increasing energy consumption. Strategies such as bioclimatic design stand out for their ability to adapt and respond to local climatic conditions, reducing reliance on HVAC systems and contributing to sustainability.

This work presents the development of a smartwatch based on open-source technologies, designed to collect data related to thermal comfort. The smartwatch allows for the collection of subjective data through simplified thermal comfort surveys and records the measurement of physiological variables, such as skin temperature and heart rate. The collected data is sent and stored on the ThingsBoard platform, enabling the creation of a contextualized database adaptable to different climatic contexts.

The smartwatch integrates low-cost components, including the XIAO ESP32C3 development board, GY-906 and MAX30102 sensors, a XIAO Round Display touchscreen, and a vibrating circuit, all encapsulated in a 3D-printed case designed for this purpose.

The development of this project encompasses the design, construction, calibration, and validation of the device. This work highlights and demonstrates the potential of open-source technologies and wearable devices in the study of thermal comfort, as well as in the generation of databases that can facilitate the creation of adaptive comfort models. In doing so, it contributes to the sustainable use of resources to achieve thermal comfort conditions. \newline

# Agradecimientos {.unnumbered}


Quiero agradecer a:

Mi tutor, Guillermo Barrios, por todo su apoyo durante esta etapa. No solo me brindó respaldo académico, sino también personal.

Mi familia, por estar siempre a mi lado y por ser mi fuente de fortaleza.

Mis amigos, ahora convertidos en familia, que hice en el Instituto de Energías Renovables. Cada uno de ellos contribuyó a hacer de esta experiencia una etapa inolvidable.





