# Desarrollo y construcción

Texto introductorio del capitulo.

## Metodología
1. **Descripción general del dispositivo:**


El dispositivo presentado en esta tesis es un prototipo de reloj inteligente diseñado específicamente para la investigación en el ámbito del confort térmico. Este dispositivo permite la recopilación de datos fisiológicos, tales como la frecuencia cardíaca y la temperatura de la piel, variables cuya relación con el confort térmico se discutió en el capítulo anterior. Además, este dispositivo realiza encuestas periódicas simplificadas de confort térmico mediante una interfaz de usuario intuitiva, que permite responder la encuesta de forma rápida y sencilla. La recopilación de estos datos se realiza en la plataforma de IoT llamada ThingsBoard, lo que permite la creación de una base de datos de confort térmico en un bioclima cálido semihúmedo [@infonavit2024regiones] en Temixco, Morelos. Esta base de datos facilitará estudios para el entendimiento del confort térmico y el desarrollo de modelos de confort para este tipo de bioclima, así como de modelos de confort personalizados.

2. **Selección de componentes** 

Para asegurar el funcionamiento preciso y adecuado del dispositivo fue fundamental la correcta elección de todos los componentes. A continuación se describen los principales componentes utilizados, sus características y justificación para el proyecto, basada en criterios como la compatibilidad, consumo de energía, precisión y capacidad de procesamiento en el caso del microcontrolador.

Los componentes principales descritos son los siguientes: 

* Placa de desarrollo
* Pantalla
* Batería 
* Sensores

Escoger la tarjeta o placa de desarrollo fue una de las partes cruciales en el desarrollo del proyecto, se necesitaba una placa de tamaño reducido que cumpliera con las características requeridas: conexión Wifi, velocidad de procesamiento, memoria, comunicación I2C...

Se buscaron placas con microcontroladores que fueran reducidas de tamaño pero con conectividad inalámbrica. Estas características nos las ofrecen microcontroladores como los de Arduino, ESP y Raspberry. La @tbl-placas muestra una comparativa básica de algunas placas con estos microcontroladores. 

Es importante mencionar que dentro de esta búsqueda se encontraron algunas placas que ya tenían integrada una pantalla LCD, lo cual podría significar una ventaja, sin embargo el microcontrolador RP2040 no cuenta con conectividad Wifi o Bluetooth, y la tarjeta LILYGO cuenta con una pantalla que no es táctil, lo que representa una desventaja para la realización de las encuestas de confort.

| Placa de desarrollo          | Wifi | Bluetooth | Comunicación                    | Cable       | Pines         |
|------------------------------|------|-----------|---------------------------------|-------------|---------------|
| Arduino Nano 33 IoT         | si   | 4.2       | SPI, I2C, I2S, UART            | Micro USB   | 14 d, 6 pwm   |
| Arduino nano 33 BLE sense   | no   | 5         | UART, SPI, I2C                 | Micro USB   | 14 d-pwm      |
| Arduino nano esp32          | si   | LE        | UART, I2C, SPI, I2S, CAN(TWAI)  | USB C       |               |
| Arduino nano RP2040 connect | si   | si        | STI, I2C, I2S, PIO, UART       | USB C       | 22 d, 2o pwm  |
| Raspberry pi pico W         | si   | 5.2       | UART, I2C, SPI                 | Micro USB   | 26 d, 16 pwm  |
| ESP32 pico kit              | si   | si        | I2C, I2S, SPI                  | Micro USB   | 34 gpios      |
| Seeed Studio XIAO nRF52840 Sense | nfc | 5  | 1xUART, 1xIIC, 1xSPI, 1xNFC, 1xSWD | USB C | 11xGPIO(PWM), 6xADC |
| Seeed Studio XIAO ESP32C3   | si   | 5         | 1x UART, 1x IIC, 1x SPI       | USB C       | 11x GPIO(PWM), 4x ADC |
| Seeed Studio XIAO ESP32S3   | si   | 5         | 1x UART, 1x IIC, 1x SPI       | USB C       | 11x GPIO(PWM), 9x ADC |
| MCU RP2040 con LCD redondo de 1,28 pulgadas | no | no | rp2040 | USB C | rp2040 |
| LILYGO TTGO                | si   | si        | esp32                         | USB C       | esp32         |
: Placas de desarrollo {#tbl-placas}

Tras investigar más a detalle las especificaciones de las placas, se elogió la Seeed Studio XIAO ESP32C3. Esta tarjeta se adapta a las necesidades por tener diferentes modos de bajo consumo, conectividad Wifi, tamaño reducido y memoria suficiente. En la @tbl-esp se muestran las características de dicha tarjeta.

También puede ser usada la tarjeta XIAO ESP32S3 que se adapta sin ningún problema al proyecto, la principal diferencia es que esta tiene mayor memoria que la XIAO ESP32C3, sin embargo, su costo es más elevado.

| Parameter                                 | Seeed Studio XIAO ESP32S3 |
|-------------------------------------------|----------------------------|
| Processor                                 | ESP32-S3R8<br>Xtensa LX7 dual-core<br>32-bit processor running<br>up to 240 MHz                                                                  
| Wireless                                  | Complete 2.4GHz WiFi subsystem<br>BLE: Bluetooth 5.0, Bluetooth mesh     
| On-chip Memory                            | 8M PSRAM & 8MB Flash        |
| Interface                                 | 1x UART, 1x IIC, 1x IIS, 1x SPI,11x GPIO(PWM), 9x ADC, 1x User LED, 1x Charge LED<br>1x Reset button, 1x Boot button                     |
| Dimensions                                | 21 x 17.5mm                |
| Power                                     | Input voltage (Type-C): 5V<br>Input voltage (BAT): 4.2V  |
|                                           | Circuit operating Voltage (ready to operate):<br>- Type-C: 5V@19mA <br>- BAT: 3.8V@22mA           |
|                                           | Charging battery current: 100mA                      |
| Low Power Consumption Model <br> (Supply Power: 3.8V)                                         | Modem-sleep Model: ~ 25 mA <br> Light-sleep Model: ~ 2mA <br> Deep Sleep Model: ~ 14 μA  |
| WiFi Enabled Power Consumption            | Active Model: ~ 100 mA     |
| BLE Enabled Power Consumption             | Active Model: ~ 85 mA      |
| Working Temperature                       | -40°C ~ 65°C               |
: Características ESP32S3 {#tbl-esp} 

 <!-- Actualizar tabla a ESP32C3 -->


Para la elección de la pantalla se realizó una búsqueda priorizando que esta fuera de tamaño reducido y adaptable a la placa de desarrollo seleccionada. 

 En la @tbl-screen se muestran las características básicas de las pantallas encontradas.

| Pantalla                                   | touchscreen | tecnología | dimensión |
|--------------------------------------------|-------------|------------|----------|
| Seeed Studio Round Display for XIAO        | si          | TFT LCD    | 1.28''   |
| Waveshare Módulo de visualización           | no          | OLED RGB   | 1.5''    |
| GC9A01 Pantalla                            | no          | TFT LCD    | 1.28''   |
: Pantallas {#tbl-screen}


La pantalla elegida fue la Seeed Studio Round Display for XIAO. La marca Seeed Studio ha desarrollado todo un ecosistema de hardware pensando en dispositivos portátiles y de tipo wearables. Su pantalla se adapta perfectamente a la placa de desarrollo, ademas de tener un display redondo y táctil, lo cual se ajusta bastante bien a lo necesitado para el proyecto.



El uso de baterías de Ion de Polímero de Litio (LiPo) es muy común en los dispositivos portátiles, esto debido a su reducido tamaño, peso y facilidad de carga. La capacidad minima de carga requerida para la placa de desarrollo en conjunto con la pantalla es de 500 mAh (cita del datasheet de la pantalla). Una batería más pequeña si bien sería un beneficio por su tamaño, implicaría una duración muy limitada. En la @tbl-bat se muestran las características de 7 baterías de diferente capacidad que tiene dimensiones reducidas y podrían adaptarse al dispositivo. 

| tipo | voltaje | capacidad | potencia | dimensiones |
|------|---------|-----------|----------|-------------|
| LiPo | 3.7     | 60 mAh    | 0.22 Wh  | 22x11.5x4 mm |
| LiPo | 3.7     | 130 mAh   | 0.48 Wh  | 30x15x3.5 mm |
| LiPo | 3.7     | 250 mAh   | 0.93 Wh  | 20x30x5 mm  |
| LiPo | 3.7     | 400 mAh   | 1.48 Wh  | 35x20x6 mm  |
| LiPo | 3.7     | 650 mAh   | 2.41 Wh  | 40x20x8 mm  |
| LiPo | 3.7     | 1000 mAh  | 3.7 Wh   | 50x34x5 mm  |
: Baterías {#tbl-bat}

Para asegurar un correcto funcionamiento del dispositivo, se eligió una batería con una capacidad de 650 mAh. Esta capacidad de carga no solo cumple con los requisitos mínimos de energía especificados en la hoja de datos del microcontrolador y la pantalla, si no que, da un margen adicional en la duración de la batería. Además de tener un tamaño adecuado para no afectar el diseño del dispositivo.

Existen 3 tipos diferentes de sensores por su funcionamiento para medir temperatura, estos son: 

* Termopares
* Termistores
* Sensores RTD 

Siendo los termistores los más utilizados en aplicaciones de la salud, como por ejemplo medir la temperatura corporal o la temperatura de la piel en algún punto. Un termistor es una resistencia eléctrica que cambia su valor dependiendo de la temperatura a la que esté expuesta, existen termistores tipo PTC que son de respuesta positiva, es decir, aumenta su resistencia cuando hay un aumento en la temperatura, de manera análoga existen los termistores tipo NTC.

Se realizó una búsqueda de diferentes termistores que pudieran ser útiles. Estos sensores son analógicos, sin embargo existen circuitos integrados que pueden convertir las señales de este sensor en digitales. La @tbl-temp muestra algunos de estos sensores con sus características básicas. 

| Sensor             | tipo         | rango           | valor          | potencia | precisión | resolución |
|--------------------|--------------|-----------------|----------------|----------|-----------|------------|
| temistor NTC MF52AT| analógico    | -40 C a 120 C   | 1k hasta 100k  | 0.5 W    |           |            |
| HiLetgo 2 unidades AHT20| digital (I2C)| -40 C a 85 C |                |     | 0.3 C    | 0.01 C
| HiLetgo SHT31-D    | digital (I2C)| -40 C a 125 C  |                |     |    0.3 C       |
| AHT10              | digital (I2C)| -40 C a 85 C   |                |    | 0.3 C    | 0.01 C
: Sensores de temperatura {#tbl-temp}


3. **Diseño del dispositivo**

## Construcción del dispositivo
Detallar cuales son los pasos para construir el dispositivo, tips, errores comunes.

## Programación de la interfaz y encuestas

1. Desarrollo del firmware: describe el desarrollo de la interfaz
2. Implementación de la encuesta: Explica detalladamente la encuesta y porque se eligieron esos preguntas

## Etapa de calibración
1. Calibración de los sensores 

## Etapa de conexión IoT
1. Integración con la plataforma